version: '3'

services:
  db:
    #image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: DATABASE
    ports:
      - "5432:5432"
    expose:
      - "5432"

  server:
    build: ./server
    container_name: golang_server
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    expose:
      - "8080"
