version: '3'

services:
  db:
    #image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: DATABASE
      #BUILD: ./DATABASE PERO AL NIVEL DE PORTS
      #POSTGRES_USER: myuser
      #POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: golang_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
