openapi: 3.0.0
info:
    title: API-REST
    description: This is a simple API-REST to do some queries to a postgres database froma  golang server
    version: 1.0.0
paths:
    /users:
        get:
        summary: Obtains a list of the users registered in the database
        responses:
            200:
            description: OK
            content:
                application/json:
                schema:
                    type: array
                    items:
                    type: object
                    properties:
                        id:
                        type: integer
                        format: int64
                        name:
                        type: string
                        email:
                        type: string